//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.15 at 10:30:36 PM CEST 
//


package model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TClanAmandnam complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TClanAmandnam">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IzmenaClana" type="{http://www.gradskaskupstina.rs/}TTekstIzmene" minOccurs="0"/>
 *         &lt;element name="StavAmandman" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IzmenaStava" type="{http://www.gradskaskupstina.rs/}TTekstIzmene" minOccurs="0"/>
 *                   &lt;element name="TackaAmandman" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="IzmenaTacke" type="{http://www.gradskaskupstina.rs/}TTekstIzmene" minOccurs="0"/>
 *                             &lt;element name="AlinejaAmandman" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Izmena" type="{http://www.gradskaskupstina.rs/}TTekstIzmene"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="OznakaAlineje" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="OznakaTacke" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="OznakaStava" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="OznakaClana" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TClanAmandnam", namespace = "http://www.gradskaskupstina.rs/", propOrder = {
    "izmenaClana",
    "stavAmandman"
})
public class TClanAmandnam {

    @XmlElement(name = "IzmenaClana")
    protected TTekstIzmene izmenaClana;
    @XmlElement(name = "StavAmandman")
    protected List<TClanAmandnam.StavAmandman> stavAmandman;
    @XmlAttribute(name = "OznakaClana")
    @XmlSchemaType(name = "anySimpleType")
    protected String oznakaClana;

    /**
     * Gets the value of the izmenaClana property.
     * 
     * @return
     *     possible object is
     *     {@link TTekstIzmene }
     *     
     */
    public TTekstIzmene getIzmenaClana() {
        return izmenaClana;
    }

    /**
     * Sets the value of the izmenaClana property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTekstIzmene }
     *     
     */
    public void setIzmenaClana(TTekstIzmene value) {
        this.izmenaClana = value;
    }

    /**
     * Gets the value of the stavAmandman property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stavAmandman property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStavAmandman().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TClanAmandnam.StavAmandman }
     * 
     * 
     */
    public List<TClanAmandnam.StavAmandman> getStavAmandman() {
        if (stavAmandman == null) {
            stavAmandman = new ArrayList<TClanAmandnam.StavAmandman>();
        }
        return this.stavAmandman;
    }

    /**
     * Gets the value of the oznakaClana property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOznakaClana() {
        return oznakaClana;
    }

    /**
     * Sets the value of the oznakaClana property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOznakaClana(String value) {
        this.oznakaClana = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IzmenaStava" type="{http://www.gradskaskupstina.rs/}TTekstIzmene" minOccurs="0"/>
     *         &lt;element name="TackaAmandman" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="IzmenaTacke" type="{http://www.gradskaskupstina.rs/}TTekstIzmene" minOccurs="0"/>
     *                   &lt;element name="AlinejaAmandman" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Izmena" type="{http://www.gradskaskupstina.rs/}TTekstIzmene"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="OznakaAlineje" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="OznakaTacke" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="OznakaStava" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "izmenaStava",
        "tackaAmandman"
    })
    public static class StavAmandman {

        @XmlElement(name = "IzmenaStava", namespace = "http://www.gradskaskupstina.rs/")
        protected TTekstIzmene izmenaStava;
        @XmlElement(name = "TackaAmandman", namespace = "http://www.gradskaskupstina.rs/")
        protected List<TClanAmandnam.StavAmandman.TackaAmandman> tackaAmandman;
        @XmlAttribute(name = "OznakaStava")
        @XmlSchemaType(name = "anySimpleType")
        protected String oznakaStava;

        /**
         * Gets the value of the izmenaStava property.
         * 
         * @return
         *     possible object is
         *     {@link TTekstIzmene }
         *     
         */
        public TTekstIzmene getIzmenaStava() {
            return izmenaStava;
        }

        /**
         * Sets the value of the izmenaStava property.
         * 
         * @param value
         *     allowed object is
         *     {@link TTekstIzmene }
         *     
         */
        public void setIzmenaStava(TTekstIzmene value) {
            this.izmenaStava = value;
        }

        /**
         * Gets the value of the tackaAmandman property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tackaAmandman property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTackaAmandman().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TClanAmandnam.StavAmandman.TackaAmandman }
         * 
         * 
         */
        public List<TClanAmandnam.StavAmandman.TackaAmandman> getTackaAmandman() {
            if (tackaAmandman == null) {
                tackaAmandman = new ArrayList<TClanAmandnam.StavAmandman.TackaAmandman>();
            }
            return this.tackaAmandman;
        }

        /**
         * Gets the value of the oznakaStava property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOznakaStava() {
            return oznakaStava;
        }

        /**
         * Sets the value of the oznakaStava property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOznakaStava(String value) {
            this.oznakaStava = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="IzmenaTacke" type="{http://www.gradskaskupstina.rs/}TTekstIzmene" minOccurs="0"/>
         *         &lt;element name="AlinejaAmandman" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Izmena" type="{http://www.gradskaskupstina.rs/}TTekstIzmene"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="OznakaAlineje" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="OznakaTacke" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "izmenaTacke",
            "alinejaAmandman"
        })
        public static class TackaAmandman {

            @XmlElement(name = "IzmenaTacke", namespace = "http://www.gradskaskupstina.rs/")
            protected TTekstIzmene izmenaTacke;
            @XmlElement(name = "AlinejaAmandman", namespace = "http://www.gradskaskupstina.rs/")
            protected List<TClanAmandnam.StavAmandman.TackaAmandman.AlinejaAmandman> alinejaAmandman;
            @XmlAttribute(name = "OznakaTacke")
            @XmlSchemaType(name = "anySimpleType")
            protected String oznakaTacke;

            /**
             * Gets the value of the izmenaTacke property.
             * 
             * @return
             *     possible object is
             *     {@link TTekstIzmene }
             *     
             */
            public TTekstIzmene getIzmenaTacke() {
                return izmenaTacke;
            }

            /**
             * Sets the value of the izmenaTacke property.
             * 
             * @param value
             *     allowed object is
             *     {@link TTekstIzmene }
             *     
             */
            public void setIzmenaTacke(TTekstIzmene value) {
                this.izmenaTacke = value;
            }

            /**
             * Gets the value of the alinejaAmandman property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the alinejaAmandman property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAlinejaAmandman().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TClanAmandnam.StavAmandman.TackaAmandman.AlinejaAmandman }
             * 
             * 
             */
            public List<TClanAmandnam.StavAmandman.TackaAmandman.AlinejaAmandman> getAlinejaAmandman() {
                if (alinejaAmandman == null) {
                    alinejaAmandman = new ArrayList<TClanAmandnam.StavAmandman.TackaAmandman.AlinejaAmandman>();
                }
                return this.alinejaAmandman;
            }

            /**
             * Gets the value of the oznakaTacke property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOznakaTacke() {
                return oznakaTacke;
            }

            /**
             * Sets the value of the oznakaTacke property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOznakaTacke(String value) {
                this.oznakaTacke = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Izmena" type="{http://www.gradskaskupstina.rs/}TTekstIzmene"/>
             *       &lt;/sequence>
             *       &lt;attribute name="OznakaAlineje" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "izmena"
            })
            public static class AlinejaAmandman {

                @XmlElement(name = "Izmena", namespace = "http://www.gradskaskupstina.rs/", required = true)
                protected TTekstIzmene izmena;
                @XmlAttribute(name = "OznakaAlineje")
                @XmlSchemaType(name = "anySimpleType")
                protected String oznakaAlineje;

                /**
                 * Gets the value of the izmena property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TTekstIzmene }
                 *     
                 */
                public TTekstIzmene getIzmena() {
                    return izmena;
                }

                /**
                 * Sets the value of the izmena property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TTekstIzmene }
                 *     
                 */
                public void setIzmena(TTekstIzmene value) {
                    this.izmena = value;
                }

                /**
                 * Gets the value of the oznakaAlineje property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOznakaAlineje() {
                    return oznakaAlineje;
                }

                /**
                 * Sets the value of the oznakaAlineje property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOznakaAlineje(String value) {
                    this.oznakaAlineje = value;
                }

            }

        }

    }

}
