//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.15 at 08:30:32 PM CEST 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TReferenca complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TReferenca">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="refAkt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="refClan" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="refStav" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TReferenca", namespace = "http://www.gradskaskupstina.rs/", propOrder = {
    "refAkt",
    "refClan",
    "refStav"
})
public class TReferenca {

    @XmlElement(required = true)
    protected String refAkt;
    @XmlElement(required = true)
    protected String refClan;
    protected String refStav;

    /**
     * Gets the value of the refAkt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefAkt() {
        return refAkt;
    }

    /**
     * Sets the value of the refAkt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefAkt(String value) {
        this.refAkt = value;
    }

    /**
     * Gets the value of the refClan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefClan() {
        return refClan;
    }

    /**
     * Sets the value of the refClan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefClan(String value) {
        this.refClan = value;
    }

    /**
     * Gets the value of the refStav property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefStav() {
        return refStav;
    }

    /**
     * Sets the value of the refStav property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefStav(String value) {
        this.refStav = value;
    }

}
