//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.15 at 08:30:32 PM CEST 
//


package model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TSadrzajTacke complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TSadrzajTacke">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TekstTacka" type="{http://www.gradskaskupstina.rs/}TTekst"/>
 *         &lt;element name="Alineja" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SadrzajAlineja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="OznakaAlineja" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TSadrzajTacke", namespace = "http://www.gradskaskupstina.rs/", propOrder = {
    "tekstTacka",
    "alineja"
})
public class TSadrzajTacke {

    @XmlElement(name = "TekstTacka", required = true)
    protected TTekst tekstTacka;
    @XmlElement(name = "Alineja")
    protected List<TSadrzajTacke.Alineja> alineja;

    /**
     * Gets the value of the tekstTacka property.
     * 
     * @return
     *     possible object is
     *     {@link TTekst }
     *     
     */
    public TTekst getTekstTacka() {
        return tekstTacka;
    }

    /**
     * Sets the value of the tekstTacka property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTekst }
     *     
     */
    public void setTekstTacka(TTekst value) {
        this.tekstTacka = value;
    }

    /**
     * Gets the value of the alineja property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alineja property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlineja().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TSadrzajTacke.Alineja }
     * 
     * 
     */
    public List<TSadrzajTacke.Alineja> getAlineja() {
        if (alineja == null) {
            alineja = new ArrayList<TSadrzajTacke.Alineja>();
        }
        return this.alineja;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SadrzajAlineja" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="OznakaAlineja" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sadrzajAlineja"
    })
    public static class Alineja {

        @XmlElement(name = "SadrzajAlineja", namespace = "http://www.gradskaskupstina.rs/", required = true)
        protected String sadrzajAlineja;
        @XmlAttribute(name = "OznakaAlineja")
        protected String oznakaAlineja;

        /**
         * Gets the value of the sadrzajAlineja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSadrzajAlineja() {
            return sadrzajAlineja;
        }

        /**
         * Sets the value of the sadrzajAlineja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSadrzajAlineja(String value) {
            this.sadrzajAlineja = value;
        }

        /**
         * Gets the value of the oznakaAlineja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOznakaAlineja() {
            return oznakaAlineja;
        }

        /**
         * Sets the value of the oznakaAlineja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOznakaAlineja(String value) {
            this.oznakaAlineja = value;
        }

    }

}
