//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.15 at 08:30:32 PM CEST 
//


package model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Preambula" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NazivAkt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;sequence>
 *           &lt;element name="Deo" type="{http://www.gradskaskupstina.rs/}TDeo" maxOccurs="unbounded"/>
 *           &lt;element name="PrelazneIZavrsneOdredbe">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Predlagac" type="{http://www.gradskaskupstina.rs/}TOdbornik"/>
 *                     &lt;element name="Datum" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TimeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "preambula",
    "nazivAkt",
    "deo",
    "prelazneIZavrsneOdredbe",
    "id",
    "timeStamp",
    "signature"
})
@XmlRootElement(name = "Akt", namespace = "http://www.gradskaskupstina.rs/")
public class Akt {

    @XmlElement(name = "Preambula", namespace = "http://www.gradskaskupstina.rs/")
    protected String preambula;
    @XmlElement(name = "NazivAkt", namespace = "http://www.gradskaskupstina.rs/", required = true)
    protected String nazivAkt;
    @XmlElement(name = "Deo", namespace = "http://www.gradskaskupstina.rs/", required = true)
    protected List<TDeo> deo;
    @XmlElement(name = "PrelazneIZavrsneOdredbe", namespace = "http://www.gradskaskupstina.rs/", required = true)
    protected Akt.PrelazneIZavrsneOdredbe prelazneIZavrsneOdredbe;
    @XmlElement(name = "Id", namespace = "http://www.gradskaskupstina.rs/")
    protected String id;
    @XmlElement(name = "TimeStamp", namespace = "http://www.gradskaskupstina.rs/")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeStamp;
    @XmlElement(name = "Signature")
    protected SignatureType signature;

    /**
     * Gets the value of the preambula property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreambula() {
        return preambula;
    }

    /**
     * Sets the value of the preambula property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreambula(String value) {
        this.preambula = value;
    }

    /**
     * Gets the value of the nazivAkt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivAkt() {
        return nazivAkt;
    }

    /**
     * Sets the value of the nazivAkt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivAkt(String value) {
        this.nazivAkt = value;
    }

    /**
     * Gets the value of the deo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TDeo }
     * 
     * 
     */
    public List<TDeo> getDeo() {
        if (deo == null) {
            deo = new ArrayList<TDeo>();
        }
        return this.deo;
    }

    /**
     * Gets the value of the prelazneIZavrsneOdredbe property.
     * 
     * @return
     *     possible object is
     *     {@link Akt.PrelazneIZavrsneOdredbe }
     *     
     */
    public Akt.PrelazneIZavrsneOdredbe getPrelazneIZavrsneOdredbe() {
        return prelazneIZavrsneOdredbe;
    }

    /**
     * Sets the value of the prelazneIZavrsneOdredbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link Akt.PrelazneIZavrsneOdredbe }
     *     
     */
    public void setPrelazneIZavrsneOdredbe(Akt.PrelazneIZavrsneOdredbe value) {
        this.prelazneIZavrsneOdredbe = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeStamp(XMLGregorianCalendar value) {
        this.timeStamp = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Predlagac" type="{http://www.gradskaskupstina.rs/}TOdbornik"/>
     *         &lt;element name="Datum" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "predlagac",
        "datum"
    })
    public static class PrelazneIZavrsneOdredbe {

        @XmlElement(name = "Predlagac", namespace = "http://www.gradskaskupstina.rs/", required = true)
        protected TOdbornik predlagac;
        @XmlElement(name = "Datum", namespace = "http://www.gradskaskupstina.rs/", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar datum;

        /**
         * Gets the value of the predlagac property.
         * 
         * @return
         *     possible object is
         *     {@link TOdbornik }
         *     
         */
        public TOdbornik getPredlagac() {
            return predlagac;
        }

        /**
         * Sets the value of the predlagac property.
         * 
         * @param value
         *     allowed object is
         *     {@link TOdbornik }
         *     
         */
        public void setPredlagac(TOdbornik value) {
            this.predlagac = value;
        }

        /**
         * Gets the value of the datum property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatum() {
            return datum;
        }

        /**
         * Sets the value of the datum property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatum(XMLGregorianCalendar value) {
            this.datum = value;
        }

    }

}
