//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.04 at 01:42:52 AM CEST 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PravniOsnov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Predlagac" type="{http://www.gradskaskupstina.rs/tipovi}TOdbornik"/>
 *         &lt;sequence>
 *           &lt;element ref="{http://www.gradskaskupstina.rs/akt}Akt"/>
 *           &lt;element name="PredmetIzmene" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="CiljIzmene" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="DatumPredlaganja" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pravniOsnov",
    "predlagac",
    "akt",
    "predmetIzmene",
    "ciljIzmene"
})
@XmlRootElement(name = "Amandman", namespace = "http://www.gradskaskupstina.rs/amandman")
public class Amandman {

    @XmlElement(name = "PravniOsnov", namespace = "http://www.gradskaskupstina.rs/amandman", required = true)
    protected String pravniOsnov;
    @XmlElement(name = "Predlagac", namespace = "http://www.gradskaskupstina.rs/amandman", required = true)
    protected TOdbornik predlagac;
    @XmlElement(name = "Akt", namespace = "http://www.gradskaskupstina.rs/akt", required = true)
    protected Akt akt;
    @XmlElement(name = "PredmetIzmene", namespace = "http://www.gradskaskupstina.rs/amandman", required = true)
    protected String predmetIzmene;
    @XmlElement(name = "CiljIzmene", namespace = "http://www.gradskaskupstina.rs/amandman", required = true)
    protected String ciljIzmene;
    @XmlAttribute(name = "DatumPredlaganja")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datumPredlaganja;

    /**
     * Gets the value of the pravniOsnov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPravniOsnov() {
        return pravniOsnov;
    }

    /**
     * Sets the value of the pravniOsnov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPravniOsnov(String value) {
        this.pravniOsnov = value;
    }

    /**
     * Gets the value of the predlagac property.
     * 
     * @return
     *     possible object is
     *     {@link TOdbornik }
     *     
     */
    public TOdbornik getPredlagac() {
        return predlagac;
    }

    /**
     * Sets the value of the predlagac property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOdbornik }
     *     
     */
    public void setPredlagac(TOdbornik value) {
        this.predlagac = value;
    }

    /**
     * Gets the value of the akt property.
     * 
     * @return
     *     possible object is
     *     {@link Akt }
     *     
     */
    public Akt getAkt() {
        return akt;
    }

    /**
     * Sets the value of the akt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Akt }
     *     
     */
    public void setAkt(Akt value) {
        this.akt = value;
    }

    /**
     * Gets the value of the predmetIzmene property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPredmetIzmene() {
        return predmetIzmene;
    }

    /**
     * Sets the value of the predmetIzmene property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPredmetIzmene(String value) {
        this.predmetIzmene = value;
    }

    /**
     * Gets the value of the ciljIzmene property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCiljIzmene() {
        return ciljIzmene;
    }

    /**
     * Sets the value of the ciljIzmene property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCiljIzmene(String value) {
        this.ciljIzmene = value;
    }

    /**
     * Gets the value of the datumPredlaganja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPredlaganja() {
        return datumPredlaganja;
    }

    /**
     * Sets the value of the datumPredlaganja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPredlaganja(XMLGregorianCalendar value) {
        this.datumPredlaganja = value;
    }

}
