//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.11 at 04:17:18 PM CEST 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PravniOsnov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Predlagac" type="{http://www.gradskaskupstina.rs/}TOdbornik"/>
 *         &lt;element name="SadrzajAmandmana" type="{http://www.gradskaskupstina.rs/}TSadrzajAmandmana"/>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Signature" type="{http://www.w3.org/2000/09/xmldsig#}SignatureType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DatumPredlaganja" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pravniOsnov",
    "predlagac",
    "sadrzajAmandmana",
    "id",
    "timestamp",
    "signature"
})
@XmlRootElement(name = "Amandman", namespace = "http://www.gradskaskupstina.rs/")
public class Amandman {

    @XmlElement(name = "PravniOsnov", namespace = "http://www.gradskaskupstina.rs/", required = true)
    protected String pravniOsnov;
    @XmlElement(name = "Predlagac", namespace = "http://www.gradskaskupstina.rs/", required = true)
    protected TOdbornik predlagac;
    @XmlElement(name = "SadrzajAmandmana", namespace = "http://www.gradskaskupstina.rs/", required = true)
    protected TSadrzajAmandmana sadrzajAmandmana;
    @XmlElement(name = "ID", namespace = "http://www.gradskaskupstina.rs/")
    protected String id;
    @XmlElement(name = "Timestamp", namespace = "http://www.gradskaskupstina.rs/")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;
    @XmlElement(name = "Signature", namespace = "http://www.gradskaskupstina.rs/")
    protected SignatureType signature;
    @XmlAttribute(name = "DatumPredlaganja")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datumPredlaganja;

    /**
     * Gets the value of the pravniOsnov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPravniOsnov() {
        return pravniOsnov;
    }

    /**
     * Sets the value of the pravniOsnov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPravniOsnov(String value) {
        this.pravniOsnov = value;
    }

    /**
     * Gets the value of the predlagac property.
     * 
     * @return
     *     possible object is
     *     {@link TOdbornik }
     *     
     */
    public TOdbornik getPredlagac() {
        return predlagac;
    }

    /**
     * Sets the value of the predlagac property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOdbornik }
     *     
     */
    public void setPredlagac(TOdbornik value) {
        this.predlagac = value;
    }

    /**
     * Gets the value of the sadrzajAmandmana property.
     * 
     * @return
     *     possible object is
     *     {@link TSadrzajAmandmana }
     *     
     */
    public TSadrzajAmandmana getSadrzajAmandmana() {
        return sadrzajAmandmana;
    }

    /**
     * Sets the value of the sadrzajAmandmana property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSadrzajAmandmana }
     *     
     */
    public void setSadrzajAmandmana(TSadrzajAmandmana value) {
        this.sadrzajAmandmana = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

    /**
     * Gets the value of the datumPredlaganja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPredlaganja() {
        return datumPredlaganja;
    }

    /**
     * Sets the value of the datumPredlaganja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPredlaganja(XMLGregorianCalendar value) {
        this.datumPredlaganja = value;
    }

}
