//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.04 at 01:42:52 AM CEST 
//


package model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TSadrzajGlaveClan_QNAME = new QName("http://www.gradskaskupstina.rs/tipovi", "Clan");
    private final static QName _TSadrzajGlaveOdeljak_QNAME = new QName("http://www.gradskaskupstina.rs/tipovi", "Odeljak");
    private final static QName _TSadrzajDelaGlava_QNAME = new QName("http://www.gradskaskupstina.rs/tipovi", "Glava");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TSadrzajGlave }
     * 
     */
    public TSadrzajGlave createTSadrzajGlave() {
        return new TSadrzajGlave();
    }

    /**
     * Create an instance of {@link TSadrzajTacke }
     * 
     */
    public TSadrzajTacke createTSadrzajTacke() {
        return new TSadrzajTacke();
    }

    /**
     * Create an instance of {@link TSadrzajClana }
     * 
     */
    public TSadrzajClana createTSadrzajClana() {
        return new TSadrzajClana();
    }

    /**
     * Create an instance of {@link TSadrzajStava }
     * 
     */
    public TSadrzajStava createTSadrzajStava() {
        return new TSadrzajStava();
    }

    /**
     * Create an instance of {@link TSadrzajOdeljka }
     * 
     */
    public TSadrzajOdeljka createTSadrzajOdeljka() {
        return new TSadrzajOdeljka();
    }

    /**
     * Create an instance of {@link TSadrzajDela }
     * 
     */
    public TSadrzajDela createTSadrzajDela() {
        return new TSadrzajDela();
    }

    /**
     * Create an instance of {@link Amandman }
     * 
     */
    public Amandman createAmandman() {
        return new Amandman();
    }

    /**
     * Create an instance of {@link TOdbornik }
     * 
     */
    public TOdbornik createTOdbornik() {
        return new TOdbornik();
    }

    /**
     * Create an instance of {@link Akt }
     * 
     */
    public Akt createAkt() {
        return new Akt();
    }

    /**
     * Create an instance of {@link Deo }
     * 
     */
    public Deo createDeo() {
        return new Deo();
    }

    /**
     * Create an instance of {@link PrelazneIZavrsneOdredbe }
     * 
     */
    public PrelazneIZavrsneOdredbe createPrelazneIZavrsneOdredbe() {
        return new PrelazneIZavrsneOdredbe();
    }

    /**
     * Create an instance of {@link model.Odeljak }
     * 
     */
    public model.Odeljak createOdeljak() {
        return new model.Odeljak();
    }

    /**
     * Create an instance of {@link model.Stav }
     * 
     */
    public model.Stav createStav() {
        return new model.Stav();
    }

    /**
     * Create an instance of {@link model.Alineja }
     * 
     */
    public model.Alineja createAlineja() {
        return new model.Alineja();
    }

    /**
     * Create an instance of {@link model.Clan }
     * 
     */
    public model.Clan createClan() {
        return new model.Clan();
    }

    /**
     * Create an instance of {@link model.Tacka }
     * 
     */
    public model.Tacka createTacka() {
        return new model.Tacka();
    }

    /**
     * Create an instance of {@link model.Glava }
     * 
     */
    public model.Glava createGlava() {
        return new model.Glava();
    }

    /**
     * Create an instance of {@link Referenca }
     * 
     */
    public Referenca createReferenca() {
        return new Referenca();
    }

    /**
     * Create an instance of {@link TGradjanin }
     * 
     */
    public TGradjanin createTGradjanin() {
        return new TGradjanin();
    }

    /**
     * Create an instance of {@link TPredsednikSkupstine }
     * 
     */
    public TPredsednikSkupstine createTPredsednikSkupstine() {
        return new TPredsednikSkupstine();
    }

    /**
     * Create an instance of {@link TSadrzajGlave.Odeljak }
     * 
     */
    public TSadrzajGlave.Odeljak createTSadrzajGlaveOdeljak() {
        return new TSadrzajGlave.Odeljak();
    }

    /**
     * Create an instance of {@link TSadrzajGlave.Clan }
     * 
     */
    public TSadrzajGlave.Clan createTSadrzajGlaveClan() {
        return new TSadrzajGlave.Clan();
    }

    /**
     * Create an instance of {@link TSadrzajTacke.Alineja }
     * 
     */
    public TSadrzajTacke.Alineja createTSadrzajTackeAlineja() {
        return new TSadrzajTacke.Alineja();
    }

    /**
     * Create an instance of {@link TSadrzajClana.Stav }
     * 
     */
    public TSadrzajClana.Stav createTSadrzajClanaStav() {
        return new TSadrzajClana.Stav();
    }

    /**
     * Create an instance of {@link TSadrzajStava.Tacka }
     * 
     */
    public TSadrzajStava.Tacka createTSadrzajStavaTacka() {
        return new TSadrzajStava.Tacka();
    }

    /**
     * Create an instance of {@link TSadrzajOdeljka.Clan }
     * 
     */
    public TSadrzajOdeljka.Clan createTSadrzajOdeljkaClan() {
        return new TSadrzajOdeljka.Clan();
    }

    /**
     * Create an instance of {@link TSadrzajDela.Glava }
     * 
     */
    public TSadrzajDela.Glava createTSadrzajDelaGlava() {
        return new TSadrzajDela.Glava();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TSadrzajGlave.Clan }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gradskaskupstina.rs/tipovi", name = "Clan", scope = TSadrzajGlave.class)
    public JAXBElement<TSadrzajGlave.Clan> createTSadrzajGlaveClan(TSadrzajGlave.Clan value) {
        return new JAXBElement<TSadrzajGlave.Clan>(_TSadrzajGlaveClan_QNAME, TSadrzajGlave.Clan.class, TSadrzajGlave.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TSadrzajGlave.Odeljak }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gradskaskupstina.rs/tipovi", name = "Odeljak", scope = TSadrzajGlave.class)
    public JAXBElement<TSadrzajGlave.Odeljak> createTSadrzajGlaveOdeljak(TSadrzajGlave.Odeljak value) {
        return new JAXBElement<TSadrzajGlave.Odeljak>(_TSadrzajGlaveOdeljak_QNAME, TSadrzajGlave.Odeljak.class, TSadrzajGlave.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TSadrzajOdeljka.Clan }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gradskaskupstina.rs/tipovi", name = "Clan", scope = TSadrzajOdeljka.class)
    public JAXBElement<TSadrzajOdeljka.Clan> createTSadrzajOdeljkaClan(TSadrzajOdeljka.Clan value) {
        return new JAXBElement<TSadrzajOdeljka.Clan>(_TSadrzajGlaveClan_QNAME, TSadrzajOdeljka.Clan.class, TSadrzajOdeljka.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TSadrzajDela.Glava }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gradskaskupstina.rs/tipovi", name = "Glava", scope = TSadrzajDela.class)
    public JAXBElement<TSadrzajDela.Glava> createTSadrzajDelaGlava(TSadrzajDela.Glava value) {
        return new JAXBElement<TSadrzajDela.Glava>(_TSadrzajDelaGlava_QNAME, TSadrzajDela.Glava.class, TSadrzajDela.class, value);
    }

}
