//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.06 at 09:49:04 PM CEST 
//


package model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Korisnici }
     * 
     */
    public Korisnici createKorisnici() {
        return new Korisnici();
    }

    /**
     * Create an instance of {@link TKorisnik }
     * 
     */
    public TKorisnik createTKorisnik() {
        return new TKorisnik();
    }
    
    /**
     * Create an instance of {@link TSadrzajStava }
     * 
     */
    public TSadrzajStava createTSadrzajStava() {
        return new TSadrzajStava();
    }

    /**
     * Create an instance of {@link TSadrzajGlave }
     * 
     */
    public TSadrzajGlave createTSadrzajGlave() {
        return new TSadrzajGlave();
    }

    /**
     * Create an instance of {@link TSadrzajTacke }
     * 
     */
    public TSadrzajTacke createTSadrzajTacke() {
        return new TSadrzajTacke();
    }

    /**
     * Create an instance of {@link TSadrzajClana }
     * 
     */
    public TSadrzajClana createTSadrzajClana() {
        return new TSadrzajClana();
    }

    /**
     * Create an instance of {@link TSadrzajOdeljka }
     * 
     */
    public TSadrzajOdeljka createTSadrzajOdeljka() {
        return new TSadrzajOdeljka();
    }

    /**
     * Create an instance of {@link TSadrzajDela }
     * 
     */
    public TSadrzajDela createTSadrzajDela() {
        return new TSadrzajDela();
    }

    /**
     * Create an instance of {@link Referenca }
     * 
     */
    public Referenca createReferenca() {
        return new Referenca();
    }

    /**
     * Create an instance of {@link Deo }
     * 
     */
    public Deo createDeo() {
        return new Deo();
    }

    /**
     * Create an instance of {@link PrelazneIZavrsneOdredbe }
     * 
     */
    public PrelazneIZavrsneOdredbe createPrelazneIZavrsneOdredbe() {
        return new PrelazneIZavrsneOdredbe();
    }

    /**
     * Create an instance of {@link TOdbornik }
     * 
     */
    public TOdbornik createTOdbornik() {
        return new TOdbornik();
    }

    /**
     * Create an instance of {@link Akt }
     * 
     */
    public Akt createAkt() {
        return new Akt();
    }

    /**
     * Create an instance of {@link TGradjanin }
     * 
     */
    public TGradjanin createTGradjanin() {
        return new TGradjanin();
    }

    /**
     * Create an instance of {@link TPredsednikSkupstine }
     * 
     */
    public TPredsednikSkupstine createTPredsednikSkupstine() {
        return new TPredsednikSkupstine();
    }

    /**
     * Create an instance of {@link TSadrzajStava.Tacka }
     * 
     */
    public TSadrzajStava.Tacka createTSadrzajStavaTacka() {
        return new TSadrzajStava.Tacka();
    }

    /**
     * Create an instance of {@link TSadrzajGlave.Odeljak }
     * 
     */
    public TSadrzajGlave.Odeljak createTSadrzajGlaveOdeljak() {
        return new TSadrzajGlave.Odeljak();
    }

    /**
     * Create an instance of {@link TSadrzajGlave.Clan }
     * 
     */
    public TSadrzajGlave.Clan createTSadrzajGlaveClan() {
        return new TSadrzajGlave.Clan();
    }

    /**
     * Create an instance of {@link TSadrzajTacke.Alineja }
     * 
     */
    public TSadrzajTacke.Alineja createTSadrzajTackeAlineja() {
        return new TSadrzajTacke.Alineja();
    }

    /**
     * Create an instance of {@link TSadrzajClana.Stav }
     * 
     */
    public TSadrzajClana.Stav createTSadrzajClanaStav() {
        return new TSadrzajClana.Stav();
    }

    /**
     * Create an instance of {@link TSadrzajOdeljka.Clan }
     * 
     */
    public TSadrzajOdeljka.Clan createTSadrzajOdeljkaClan() {
        return new TSadrzajOdeljka.Clan();
    }

    /**
     * Create an instance of {@link TSadrzajDela.Glava }
     * 
     */
    public TSadrzajDela.Glava createTSadrzajDelaGlava() {
        return new TSadrzajDela.Glava();
    }


}
