//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.15 at 08:30:32 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/2000/09/xmldsig#",xmlns = {@XmlNs(prefix = "", namespaceURI = "http://www.gradskaskupstina.gov/")}, elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package model;
import javax.xml.bind.annotation.XmlNs;

