//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.11 at 04:56:55 PM CEST 
//


package model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TSadrzajAmandmana complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TSadrzajAmandmana">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GlavaAmandman" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="OdeljakAmandman" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence minOccurs="0">
 *                             &lt;element name="ClanAmandnam" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence minOccurs="0">
 *                                       &lt;element name="StavAmandman" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence minOccurs="0">
 *                                                 &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene" minOccurs="0"/>
 *                                                 &lt;element name="TackaAmandman" maxOccurs="unbounded" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence minOccurs="0">
 *                                                           &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene" minOccurs="0"/>
 *                                                           &lt;element name="AlinejaAmandman" maxOccurs="unbounded" minOccurs="0">
 *                                                             &lt;complexType>
 *                                                               &lt;complexContent>
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                   &lt;sequence>
 *                                                                     &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene"/>
 *                                                                   &lt;/sequence>
 *                                                                   &lt;attribute name="OznakaAlineje" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                                                 &lt;/restriction>
 *                                                               &lt;/complexContent>
 *                                                             &lt;/complexType>
 *                                                           &lt;/element>
 *                                                         &lt;/sequence>
 *                                                         &lt;attribute name="OznakaTacke" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="OznakaStava" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="OznakaClana" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="OznakaOdeljka" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ClanAmandnam" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence minOccurs="0">
 *                             &lt;element name="StavAmandman" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence minOccurs="0">
 *                                       &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene" minOccurs="0"/>
 *                                       &lt;element name="TackaAmandman" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence minOccurs="0">
 *                                                 &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene" minOccurs="0"/>
 *                                                 &lt;element name="AlinejaAmandman" maxOccurs="unbounded" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene"/>
 *                                                         &lt;/sequence>
 *                                                         &lt;attribute name="OznakaAlineje" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="OznakaTacke" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="OznakaStava" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="OznakaClana" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Oznaka" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PredmetIzmene" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CiljIzmene" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="NazivAkta" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TSadrzajAmandmana", namespace = "http://www.gradskaskupstina.rs/", propOrder = {
    "glavaAmandman",
    "predmetIzmene",
    "ciljIzmene"
})
public class TSadrzajAmandmana {

    @XmlElement(name = "GlavaAmandman")
    protected List<TSadrzajAmandmana.GlavaAmandman> glavaAmandman;
    @XmlElement(name = "PredmetIzmene", required = true)
    protected String predmetIzmene;
    @XmlElement(name = "CiljIzmene", required = true)
    protected String ciljIzmene;
    @XmlAttribute(name = "NazivAkta")
    protected String nazivAkta;

    /**
     * Gets the value of the glavaAmandman property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the glavaAmandman property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGlavaAmandman().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TSadrzajAmandmana.GlavaAmandman }
     * 
     * 
     */
    public List<TSadrzajAmandmana.GlavaAmandman> getGlavaAmandman() {
        if (glavaAmandman == null) {
            glavaAmandman = new ArrayList<TSadrzajAmandmana.GlavaAmandman>();
        }
        return this.glavaAmandman;
    }

    /**
     * Gets the value of the predmetIzmene property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPredmetIzmene() {
        return predmetIzmene;
    }

    /**
     * Sets the value of the predmetIzmene property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPredmetIzmene(String value) {
        this.predmetIzmene = value;
    }

    /**
     * Gets the value of the ciljIzmene property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCiljIzmene() {
        return ciljIzmene;
    }

    /**
     * Sets the value of the ciljIzmene property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCiljIzmene(String value) {
        this.ciljIzmene = value;
    }

    /**
     * Gets the value of the nazivAkta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivAkta() {
        return nazivAkta;
    }

    /**
     * Sets the value of the nazivAkta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivAkta(String value) {
        this.nazivAkta = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="OdeljakAmandman" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence minOccurs="0">
     *                   &lt;element name="ClanAmandnam" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence minOccurs="0">
     *                             &lt;element name="StavAmandman" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence minOccurs="0">
     *                                       &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene" minOccurs="0"/>
     *                                       &lt;element name="TackaAmandman" maxOccurs="unbounded" minOccurs="0">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence minOccurs="0">
     *                                                 &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene" minOccurs="0"/>
     *                                                 &lt;element name="AlinejaAmandman" maxOccurs="unbounded" minOccurs="0">
     *                                                   &lt;complexType>
     *                                                     &lt;complexContent>
     *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                         &lt;sequence>
     *                                                           &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene"/>
     *                                                         &lt;/sequence>
     *                                                         &lt;attribute name="OznakaAlineje" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                                                       &lt;/restriction>
     *                                                     &lt;/complexContent>
     *                                                   &lt;/complexType>
     *                                                 &lt;/element>
     *                                               &lt;/sequence>
     *                                               &lt;attribute name="OznakaTacke" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="OznakaStava" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="OznakaClana" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="OznakaOdeljka" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ClanAmandnam" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence minOccurs="0">
     *                   &lt;element name="StavAmandman" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence minOccurs="0">
     *                             &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene" minOccurs="0"/>
     *                             &lt;element name="TackaAmandman" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence minOccurs="0">
     *                                       &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene" minOccurs="0"/>
     *                                       &lt;element name="AlinejaAmandman" maxOccurs="unbounded" minOccurs="0">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene"/>
     *                                               &lt;/sequence>
     *                                               &lt;attribute name="OznakaAlineje" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="OznakaTacke" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="OznakaStava" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="OznakaClana" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="Oznaka" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "odeljakAmandman",
        "clanAmandnam"
    })
    public static class GlavaAmandman {

        @XmlElement(name = "OdeljakAmandman", namespace = "http://www.gradskaskupstina.rs/")
        protected List<TSadrzajAmandmana.GlavaAmandman.OdeljakAmandman> odeljakAmandman;
        @XmlElement(name = "ClanAmandnam", namespace = "http://www.gradskaskupstina.rs/")
        protected List<TSadrzajAmandmana.GlavaAmandman.ClanAmandnam> clanAmandnam;
        @XmlAttribute(name = "Oznaka")
        protected String oznaka;

        /**
         * Gets the value of the odeljakAmandman property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the odeljakAmandman property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOdeljakAmandman().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TSadrzajAmandmana.GlavaAmandman.OdeljakAmandman }
         * 
         * 
         */
        public List<TSadrzajAmandmana.GlavaAmandman.OdeljakAmandman> getOdeljakAmandman() {
            if (odeljakAmandman == null) {
                odeljakAmandman = new ArrayList<TSadrzajAmandmana.GlavaAmandman.OdeljakAmandman>();
            }
            return this.odeljakAmandman;
        }

        /**
         * Gets the value of the clanAmandnam property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the clanAmandnam property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getClanAmandnam().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TSadrzajAmandmana.GlavaAmandman.ClanAmandnam }
         * 
         * 
         */
        public List<TSadrzajAmandmana.GlavaAmandman.ClanAmandnam> getClanAmandnam() {
            if (clanAmandnam == null) {
                clanAmandnam = new ArrayList<TSadrzajAmandmana.GlavaAmandman.ClanAmandnam>();
            }
            return this.clanAmandnam;
        }

        /**
         * Gets the value of the oznaka property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOznaka() {
            return oznaka;
        }

        /**
         * Sets the value of the oznaka property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOznaka(String value) {
            this.oznaka = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence minOccurs="0">
         *         &lt;element name="StavAmandman" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence minOccurs="0">
         *                   &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene" minOccurs="0"/>
         *                   &lt;element name="TackaAmandman" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence minOccurs="0">
         *                             &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene" minOccurs="0"/>
         *                             &lt;element name="AlinejaAmandman" maxOccurs="unbounded" minOccurs="0">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene"/>
         *                                     &lt;/sequence>
         *                                     &lt;attribute name="OznakaAlineje" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                           &lt;attribute name="OznakaTacke" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="OznakaStava" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="OznakaClana" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "stavAmandman"
        })
        public static class ClanAmandnam {

            @XmlElement(name = "StavAmandman", namespace = "http://www.gradskaskupstina.rs/")
            protected List<TSadrzajAmandmana.GlavaAmandman.ClanAmandnam.StavAmandman> stavAmandman;
            @XmlAttribute(name = "OznakaClana")
            @XmlSchemaType(name = "anySimpleType")
            protected String oznakaClana;

            /**
             * Gets the value of the stavAmandman property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the stavAmandman property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getStavAmandman().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TSadrzajAmandmana.GlavaAmandman.ClanAmandnam.StavAmandman }
             * 
             * 
             */
            public List<TSadrzajAmandmana.GlavaAmandman.ClanAmandnam.StavAmandman> getStavAmandman() {
                if (stavAmandman == null) {
                    stavAmandman = new ArrayList<TSadrzajAmandmana.GlavaAmandman.ClanAmandnam.StavAmandman>();
                }
                return this.stavAmandman;
            }

            /**
             * Gets the value of the oznakaClana property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOznakaClana() {
                return oznakaClana;
            }

            /**
             * Sets the value of the oznakaClana property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOznakaClana(String value) {
                this.oznakaClana = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence minOccurs="0">
             *         &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene" minOccurs="0"/>
             *         &lt;element name="TackaAmandman" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence minOccurs="0">
             *                   &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene" minOccurs="0"/>
             *                   &lt;element name="AlinejaAmandman" maxOccurs="unbounded" minOccurs="0">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene"/>
             *                           &lt;/sequence>
             *                           &lt;attribute name="OznakaAlineje" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *                 &lt;attribute name="OznakaTacke" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="OznakaStava" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "tekstIzmene",
                "tackaAmandman"
            })
            public static class StavAmandman {

                @XmlElement(name = "TekstIzmene", namespace = "http://www.gradskaskupstina.rs/")
                protected String tekstIzmene;
                @XmlElement(name = "TackaAmandman", namespace = "http://www.gradskaskupstina.rs/")
                protected List<TSadrzajAmandmana.GlavaAmandman.ClanAmandnam.StavAmandman.TackaAmandman> tackaAmandman;
                @XmlAttribute(name = "OznakaStava")
                @XmlSchemaType(name = "anySimpleType")
                protected String oznakaStava;

                /**
                 * Gets the value of the tekstIzmene property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTekstIzmene() {
                    return tekstIzmene;
                }

                /**
                 * Sets the value of the tekstIzmene property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTekstIzmene(String value) {
                    this.tekstIzmene = value;
                }

                /**
                 * Gets the value of the tackaAmandman property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the tackaAmandman property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getTackaAmandman().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link TSadrzajAmandmana.GlavaAmandman.ClanAmandnam.StavAmandman.TackaAmandman }
                 * 
                 * 
                 */
                public List<TSadrzajAmandmana.GlavaAmandman.ClanAmandnam.StavAmandman.TackaAmandman> getTackaAmandman() {
                    if (tackaAmandman == null) {
                        tackaAmandman = new ArrayList<TSadrzajAmandmana.GlavaAmandman.ClanAmandnam.StavAmandman.TackaAmandman>();
                    }
                    return this.tackaAmandman;
                }

                /**
                 * Gets the value of the oznakaStava property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOznakaStava() {
                    return oznakaStava;
                }

                /**
                 * Sets the value of the oznakaStava property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOznakaStava(String value) {
                    this.oznakaStava = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence minOccurs="0">
                 *         &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene" minOccurs="0"/>
                 *         &lt;element name="AlinejaAmandman" maxOccurs="unbounded" minOccurs="0">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene"/>
                 *                 &lt;/sequence>
                 *                 &lt;attribute name="OznakaAlineje" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *       &lt;attribute name="OznakaTacke" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "tekstIzmene",
                    "alinejaAmandman"
                })
                public static class TackaAmandman {

                    @XmlElement(name = "TekstIzmene", namespace = "http://www.gradskaskupstina.rs/")
                    protected String tekstIzmene;
                    @XmlElement(name = "AlinejaAmandman", namespace = "http://www.gradskaskupstina.rs/")
                    protected List<TSadrzajAmandmana.GlavaAmandman.ClanAmandnam.StavAmandman.TackaAmandman.AlinejaAmandman> alinejaAmandman;
                    @XmlAttribute(name = "OznakaTacke")
                    @XmlSchemaType(name = "anySimpleType")
                    protected String oznakaTacke;

                    /**
                     * Gets the value of the tekstIzmene property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTekstIzmene() {
                        return tekstIzmene;
                    }

                    /**
                     * Sets the value of the tekstIzmene property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTekstIzmene(String value) {
                        this.tekstIzmene = value;
                    }

                    /**
                     * Gets the value of the alinejaAmandman property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the alinejaAmandman property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getAlinejaAmandman().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link TSadrzajAmandmana.GlavaAmandman.ClanAmandnam.StavAmandman.TackaAmandman.AlinejaAmandman }
                     * 
                     * 
                     */
                    public List<TSadrzajAmandmana.GlavaAmandman.ClanAmandnam.StavAmandman.TackaAmandman.AlinejaAmandman> getAlinejaAmandman() {
                        if (alinejaAmandman == null) {
                            alinejaAmandman = new ArrayList<TSadrzajAmandmana.GlavaAmandman.ClanAmandnam.StavAmandman.TackaAmandman.AlinejaAmandman>();
                        }
                        return this.alinejaAmandman;
                    }

                    /**
                     * Gets the value of the oznakaTacke property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getOznakaTacke() {
                        return oznakaTacke;
                    }

                    /**
                     * Sets the value of the oznakaTacke property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setOznakaTacke(String value) {
                        this.oznakaTacke = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene"/>
                     *       &lt;/sequence>
                     *       &lt;attribute name="OznakaAlineje" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "tekstIzmene"
                    })
                    public static class AlinejaAmandman {

                        @XmlElement(name = "TekstIzmene", namespace = "http://www.gradskaskupstina.rs/", required = true)
                        protected String tekstIzmene;
                        @XmlAttribute(name = "OznakaAlineje")
                        @XmlSchemaType(name = "anySimpleType")
                        protected String oznakaAlineje;

                        /**
                         * Gets the value of the tekstIzmene property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getTekstIzmene() {
                            return tekstIzmene;
                        }

                        /**
                         * Sets the value of the tekstIzmene property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setTekstIzmene(String value) {
                            this.tekstIzmene = value;
                        }

                        /**
                         * Gets the value of the oznakaAlineje property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getOznakaAlineje() {
                            return oznakaAlineje;
                        }

                        /**
                         * Sets the value of the oznakaAlineje property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setOznakaAlineje(String value) {
                            this.oznakaAlineje = value;
                        }

                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence minOccurs="0">
         *         &lt;element name="ClanAmandnam" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence minOccurs="0">
         *                   &lt;element name="StavAmandman" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence minOccurs="0">
         *                             &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene" minOccurs="0"/>
         *                             &lt;element name="TackaAmandman" maxOccurs="unbounded" minOccurs="0">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence minOccurs="0">
         *                                       &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene" minOccurs="0"/>
         *                                       &lt;element name="AlinejaAmandman" maxOccurs="unbounded" minOccurs="0">
         *                                         &lt;complexType>
         *                                           &lt;complexContent>
         *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                               &lt;sequence>
         *                                                 &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene"/>
         *                                               &lt;/sequence>
         *                                               &lt;attribute name="OznakaAlineje" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *                                             &lt;/restriction>
         *                                           &lt;/complexContent>
         *                                         &lt;/complexType>
         *                                       &lt;/element>
         *                                     &lt;/sequence>
         *                                     &lt;attribute name="OznakaTacke" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                           &lt;attribute name="OznakaStava" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="OznakaClana" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="OznakaOdeljka" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "clanAmandnam"
        })
        public static class OdeljakAmandman {

            @XmlElement(name = "ClanAmandnam", namespace = "http://www.gradskaskupstina.rs/")
            protected List<TSadrzajAmandmana.GlavaAmandman.OdeljakAmandman.ClanAmandnam> clanAmandnam;
            @XmlAttribute(name = "OznakaOdeljka")
            @XmlSchemaType(name = "anySimpleType")
            protected String oznakaOdeljka;

            /**
             * Gets the value of the clanAmandnam property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the clanAmandnam property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getClanAmandnam().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TSadrzajAmandmana.GlavaAmandman.OdeljakAmandman.ClanAmandnam }
             * 
             * 
             */
            public List<TSadrzajAmandmana.GlavaAmandman.OdeljakAmandman.ClanAmandnam> getClanAmandnam() {
                if (clanAmandnam == null) {
                    clanAmandnam = new ArrayList<TSadrzajAmandmana.GlavaAmandman.OdeljakAmandman.ClanAmandnam>();
                }
                return this.clanAmandnam;
            }

            /**
             * Gets the value of the oznakaOdeljka property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOznakaOdeljka() {
                return oznakaOdeljka;
            }

            /**
             * Sets the value of the oznakaOdeljka property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOznakaOdeljka(String value) {
                this.oznakaOdeljka = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence minOccurs="0">
             *         &lt;element name="StavAmandman" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence minOccurs="0">
             *                   &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene" minOccurs="0"/>
             *                   &lt;element name="TackaAmandman" maxOccurs="unbounded" minOccurs="0">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence minOccurs="0">
             *                             &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene" minOccurs="0"/>
             *                             &lt;element name="AlinejaAmandman" maxOccurs="unbounded" minOccurs="0">
             *                               &lt;complexType>
             *                                 &lt;complexContent>
             *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                                     &lt;sequence>
             *                                       &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene"/>
             *                                     &lt;/sequence>
             *                                     &lt;attribute name="OznakaAlineje" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *                                   &lt;/restriction>
             *                                 &lt;/complexContent>
             *                               &lt;/complexType>
             *                             &lt;/element>
             *                           &lt;/sequence>
             *                           &lt;attribute name="OznakaTacke" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *                 &lt;attribute name="OznakaStava" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="OznakaClana" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "stavAmandman"
            })
            public static class ClanAmandnam {

                @XmlElement(name = "StavAmandman", namespace = "http://www.gradskaskupstina.rs/")
                protected List<TSadrzajAmandmana.GlavaAmandman.OdeljakAmandman.ClanAmandnam.StavAmandman> stavAmandman;
                @XmlAttribute(name = "OznakaClana")
                @XmlSchemaType(name = "anySimpleType")
                protected String oznakaClana;

                /**
                 * Gets the value of the stavAmandman property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the stavAmandman property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getStavAmandman().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link TSadrzajAmandmana.GlavaAmandman.OdeljakAmandman.ClanAmandnam.StavAmandman }
                 * 
                 * 
                 */
                public List<TSadrzajAmandmana.GlavaAmandman.OdeljakAmandman.ClanAmandnam.StavAmandman> getStavAmandman() {
                    if (stavAmandman == null) {
                        stavAmandman = new ArrayList<TSadrzajAmandmana.GlavaAmandman.OdeljakAmandman.ClanAmandnam.StavAmandman>();
                    }
                    return this.stavAmandman;
                }

                /**
                 * Gets the value of the oznakaClana property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOznakaClana() {
                    return oznakaClana;
                }

                /**
                 * Sets the value of the oznakaClana property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOznakaClana(String value) {
                    this.oznakaClana = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence minOccurs="0">
                 *         &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene" minOccurs="0"/>
                 *         &lt;element name="TackaAmandman" maxOccurs="unbounded" minOccurs="0">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence minOccurs="0">
                 *                   &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene" minOccurs="0"/>
                 *                   &lt;element name="AlinejaAmandman" maxOccurs="unbounded" minOccurs="0">
                 *                     &lt;complexType>
                 *                       &lt;complexContent>
                 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                           &lt;sequence>
                 *                             &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene"/>
                 *                           &lt;/sequence>
                 *                           &lt;attribute name="OznakaAlineje" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                 *                         &lt;/restriction>
                 *                       &lt;/complexContent>
                 *                     &lt;/complexType>
                 *                   &lt;/element>
                 *                 &lt;/sequence>
                 *                 &lt;attribute name="OznakaTacke" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *       &lt;attribute name="OznakaStava" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "tekstIzmene",
                    "tackaAmandman"
                })
                public static class StavAmandman {

                    @XmlElement(name = "TekstIzmene", namespace = "http://www.gradskaskupstina.rs/")
                    protected String tekstIzmene;
                    @XmlElement(name = "TackaAmandman", namespace = "http://www.gradskaskupstina.rs/")
                    protected List<TSadrzajAmandmana.GlavaAmandman.OdeljakAmandman.ClanAmandnam.StavAmandman.TackaAmandman> tackaAmandman;
                    @XmlAttribute(name = "OznakaStava")
                    @XmlSchemaType(name = "anySimpleType")
                    protected String oznakaStava;

                    /**
                     * Gets the value of the tekstIzmene property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTekstIzmene() {
                        return tekstIzmene;
                    }

                    /**
                     * Sets the value of the tekstIzmene property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTekstIzmene(String value) {
                        this.tekstIzmene = value;
                    }

                    /**
                     * Gets the value of the tackaAmandman property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the tackaAmandman property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getTackaAmandman().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link TSadrzajAmandmana.GlavaAmandman.OdeljakAmandman.ClanAmandnam.StavAmandman.TackaAmandman }
                     * 
                     * 
                     */
                    public List<TSadrzajAmandmana.GlavaAmandman.OdeljakAmandman.ClanAmandnam.StavAmandman.TackaAmandman> getTackaAmandman() {
                        if (tackaAmandman == null) {
                            tackaAmandman = new ArrayList<TSadrzajAmandmana.GlavaAmandman.OdeljakAmandman.ClanAmandnam.StavAmandman.TackaAmandman>();
                        }
                        return this.tackaAmandman;
                    }

                    /**
                     * Gets the value of the oznakaStava property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getOznakaStava() {
                        return oznakaStava;
                    }

                    /**
                     * Sets the value of the oznakaStava property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setOznakaStava(String value) {
                        this.oznakaStava = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence minOccurs="0">
                     *         &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene" minOccurs="0"/>
                     *         &lt;element name="AlinejaAmandman" maxOccurs="unbounded" minOccurs="0">
                     *           &lt;complexType>
                     *             &lt;complexContent>
                     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                 &lt;sequence>
                     *                   &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene"/>
                     *                 &lt;/sequence>
                     *                 &lt;attribute name="OznakaAlineje" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                     *               &lt;/restriction>
                     *             &lt;/complexContent>
                     *           &lt;/complexType>
                     *         &lt;/element>
                     *       &lt;/sequence>
                     *       &lt;attribute name="OznakaTacke" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "tekstIzmene",
                        "alinejaAmandman"
                    })
                    public static class TackaAmandman {

                        @XmlElement(name = "TekstIzmene", namespace = "http://www.gradskaskupstina.rs/")
                        protected String tekstIzmene;
                        @XmlElement(name = "AlinejaAmandman", namespace = "http://www.gradskaskupstina.rs/")
                        protected List<TSadrzajAmandmana.GlavaAmandman.OdeljakAmandman.ClanAmandnam.StavAmandman.TackaAmandman.AlinejaAmandman> alinejaAmandman;
                        @XmlAttribute(name = "OznakaTacke")
                        @XmlSchemaType(name = "anySimpleType")
                        protected String oznakaTacke;

                        /**
                         * Gets the value of the tekstIzmene property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getTekstIzmene() {
                            return tekstIzmene;
                        }

                        /**
                         * Sets the value of the tekstIzmene property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setTekstIzmene(String value) {
                            this.tekstIzmene = value;
                        }

                        /**
                         * Gets the value of the alinejaAmandman property.
                         * 
                         * <p>
                         * This accessor method returns a reference to the live list,
                         * not a snapshot. Therefore any modification you make to the
                         * returned list will be present inside the JAXB object.
                         * This is why there is not a <CODE>set</CODE> method for the alinejaAmandman property.
                         * 
                         * <p>
                         * For example, to add a new item, do as follows:
                         * <pre>
                         *    getAlinejaAmandman().add(newItem);
                         * </pre>
                         * 
                         * 
                         * <p>
                         * Objects of the following type(s) are allowed in the list
                         * {@link TSadrzajAmandmana.GlavaAmandman.OdeljakAmandman.ClanAmandnam.StavAmandman.TackaAmandman.AlinejaAmandman }
                         * 
                         * 
                         */
                        public List<TSadrzajAmandmana.GlavaAmandman.OdeljakAmandman.ClanAmandnam.StavAmandman.TackaAmandman.AlinejaAmandman> getAlinejaAmandman() {
                            if (alinejaAmandman == null) {
                                alinejaAmandman = new ArrayList<TSadrzajAmandmana.GlavaAmandman.OdeljakAmandman.ClanAmandnam.StavAmandman.TackaAmandman.AlinejaAmandman>();
                            }
                            return this.alinejaAmandman;
                        }

                        /**
                         * Gets the value of the oznakaTacke property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getOznakaTacke() {
                            return oznakaTacke;
                        }

                        /**
                         * Sets the value of the oznakaTacke property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setOznakaTacke(String value) {
                            this.oznakaTacke = value;
                        }


                        /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType>
                         *   &lt;complexContent>
                         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *       &lt;sequence>
                         *         &lt;element ref="{http://www.gradskaskupstina.rs/}TekstIzmene"/>
                         *       &lt;/sequence>
                         *       &lt;attribute name="OznakaAlineje" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                         *     &lt;/restriction>
                         *   &lt;/complexContent>
                         * &lt;/complexType>
                         * </pre>
                         * 
                         * 
                         */
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "tekstIzmene"
                        })
                        public static class AlinejaAmandman {

                            @XmlElement(name = "TekstIzmene", namespace = "http://www.gradskaskupstina.rs/", required = true)
                            protected String tekstIzmene;
                            @XmlAttribute(name = "OznakaAlineje")
                            @XmlSchemaType(name = "anySimpleType")
                            protected String oznakaAlineje;

                            /**
                             * Gets the value of the tekstIzmene property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link String }
                             *     
                             */
                            public String getTekstIzmene() {
                                return tekstIzmene;
                            }

                            /**
                             * Sets the value of the tekstIzmene property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link String }
                             *     
                             */
                            public void setTekstIzmene(String value) {
                                this.tekstIzmene = value;
                            }

                            /**
                             * Gets the value of the oznakaAlineje property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link String }
                             *     
                             */
                            public String getOznakaAlineje() {
                                return oznakaAlineje;
                            }

                            /**
                             * Sets the value of the oznakaAlineje property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link String }
                             *     
                             */
                            public void setOznakaAlineje(String value) {
                                this.oznakaAlineje = value;
                            }

                        }

                    }

                }

            }

        }

    }

}
