//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.15 at 08:30:32 PM CEST 
//


package model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TDeo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TDeo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Glava" maxOccurs="unbounded" minOccurs="2">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SadrzajGlava" type="{http://www.gradskaskupstina.rs/}TSadrzajGlave"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="OznakaGlava" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="NazivGlava" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="OznakaDeo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NazivDeo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TDeo", namespace = "http://www.gradskaskupstina.rs/", propOrder = {
    "glava"
})
public class TDeo {

    @XmlElement(name = "Glava", required = true)
    protected List<TDeo.Glava> glava;
    @XmlAttribute(name = "OznakaDeo")
    protected String oznakaDeo;
    @XmlAttribute(name = "NazivDeo")
    protected String nazivDeo;

    /**
     * Gets the value of the glava property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the glava property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGlava().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TDeo.Glava }
     * 
     * 
     */
    public List<TDeo.Glava> getGlava() {
        if (glava == null) {
            glava = new ArrayList<TDeo.Glava>();
        }
        return this.glava;
    }

    /**
     * Gets the value of the oznakaDeo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOznakaDeo() {
        return oznakaDeo;
    }

    /**
     * Sets the value of the oznakaDeo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOznakaDeo(String value) {
        this.oznakaDeo = value;
    }

    /**
     * Gets the value of the nazivDeo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivDeo() {
        return nazivDeo;
    }

    /**
     * Sets the value of the nazivDeo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivDeo(String value) {
        this.nazivDeo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SadrzajGlava" type="{http://www.gradskaskupstina.rs/}TSadrzajGlave"/>
     *       &lt;/sequence>
     *       &lt;attribute name="OznakaGlava" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="NazivGlava" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sadrzajGlava"
    })
    public static class Glava {

        @XmlElement(name = "SadrzajGlava", namespace = "http://www.gradskaskupstina.rs/", required = true)
        protected TSadrzajGlave sadrzajGlava;
        @XmlAttribute(name = "OznakaGlava")
        protected String oznakaGlava;
        @XmlAttribute(name = "NazivGlava")
        protected String nazivGlava;

        /**
         * Gets the value of the sadrzajGlava property.
         * 
         * @return
         *     possible object is
         *     {@link TSadrzajGlave }
         *     
         */
        public TSadrzajGlave getSadrzajGlava() {
            return sadrzajGlava;
        }

        /**
         * Sets the value of the sadrzajGlava property.
         * 
         * @param value
         *     allowed object is
         *     {@link TSadrzajGlave }
         *     
         */
        public void setSadrzajGlava(TSadrzajGlave value) {
            this.sadrzajGlava = value;
        }

        /**
         * Gets the value of the oznakaGlava property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOznakaGlava() {
            return oznakaGlava;
        }

        /**
         * Sets the value of the oznakaGlava property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOznakaGlava(String value) {
            this.oznakaGlava = value;
        }

        /**
         * Gets the value of the nazivGlava property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNazivGlava() {
            return nazivGlava;
        }

        /**
         * Sets the value of the nazivGlava property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNazivGlava(String value) {
            this.nazivGlava = value;
        }

    }

}
