//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.15 at 08:27:11 PM CEST 
//


package model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TTipIzmene complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TTipIzmene">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Dodavanje" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Izmena" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Brisanje" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TTipIzmene", namespace = "http://www.gradskaskupstina.rs/", propOrder = {
    "dodavanje",
    "izmena",
    "brisanje"
})
public class TTipIzmene {

    @XmlElement(name = "Dodavanje", defaultValue = "Dodavanje")
    protected String dodavanje;
    @XmlElement(name = "Izmena", defaultValue = "Izmena")
    protected String izmena;
    @XmlElement(name = "Brisanje", defaultValue = "Brisanje")
    protected String brisanje;

    /**
     * Gets the value of the dodavanje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDodavanje() {
        return dodavanje;
    }

    /**
     * Sets the value of the dodavanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDodavanje(String value) {
        this.dodavanje = value;
    }

    /**
     * Gets the value of the izmena property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIzmena() {
        return izmena;
    }

    /**
     * Sets the value of the izmena property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIzmena(String value) {
        this.izmena = value;
    }

    /**
     * Gets the value of the brisanje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrisanje() {
        return brisanje;
    }

    /**
     * Sets the value of the brisanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrisanje(String value) {
        this.brisanje = value;
    }

}
